import Navbaar from '@/component/Navbaar';
import Toggle from '@/component/Toggle';
import Hameburger from '@/component/Hamburger';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body>
        <Navbaar />
        <Toggle />
        <Hameburger/>
       
        {children}
      </body>
    </html>
  );
}
